keys:
  - &laptop age1r3syz7ccher088c4xfqqjh2ry0pyutdr3g6dck2phpe6pvar83jssyxpja
  - &goofy age1v665du4lh0l4lsqutquxg98kdf00yxt0ezfwdnkd32ky76als4ks5h5kn9
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
          - *laptop
          - *goofy
