# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."hydrodactyl-panel-cache" = {
    image = "redis:alpine";
    log-driver = "journald";
    extraOptions = [
      "--network-alias=cache"
      "--network=hydrodactyl-panel_default"
    ];
  };
  systemd.services."docker-hydrodactyl-panel-cache" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    unitConfig.Description = "Container hydrodactyl-panel-cache generated by compose2nix.";
    after = [
      "docker-network-hydrodactyl-panel_default.service"
    ];
    requires = [
      "docker-network-hydrodactyl-panel_default.service"
    ];
    partOf = [
      "docker-compose-hydrodactyl-panel-root.target"
    ];
    wantedBy = [
      "docker-compose-hydrodactyl-panel-root.target"
    ];
  };
  virtualisation.oci-containers.containers."hydrodactyl-panel-database" = {
    image = "mariadb:10.5";
    environment = {
      "MYSQL_DATABASE" = "panel";
      "MYSQL_PASSWORD" = "user-password";
      "MYSQL_ROOT_PASSWORD" = "root-password";
      "MYSQL_USER" = "pterodactyl";
    };
    volumes = [
      "/srv/pterodactyl/database:/var/lib/mysql:rw"
    ];
    cmd = [ "--default-authentication-plugin=mysql_native_password" ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=database"
      "--network=hydrodactyl-panel_default"
    ];
  };
  systemd.services."docker-hydrodactyl-panel-database" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    unitConfig.Description = "Container hydrodactyl-panel-database generated by compose2nix.";
    after = [
      "docker-network-hydrodactyl-panel_default.service"
    ];
    requires = [
      "docker-network-hydrodactyl-panel_default.service"
    ];
    partOf = [
      "docker-compose-hydrodactyl-panel-root.target"
    ];
    wantedBy = [
      "docker-compose-hydrodactyl-panel-root.target"
    ];
  };
  virtualisation.oci-containers.containers."hydrodactyl-panel-panel" = {
    image = "ghcr.io/blueprintframework/hydrodactyl:latest";
    environment = {
      "APP_ENV" = "production";
      "APP_ENVIRONMENT_ONLY" = "false";
      "APP_SERVICE_AUTHOR" = "rebelhamster@gmail.com";
      "APP_TIMEZONE" = "Australia/Sydney";
      "APP_URL" = "https://panel.toadhog.com";
      "CACHE_DRIVER" = "redis";
      "DB_CONNECTION" = "mariadb";
      "DB_HOST" = "database";
      "DB_PASSWORD" = "user-password";
      "DB_PORT" = "3306";
      "DB_USERNAME" = "pterodactyl";
      "HASHIDS_LENGTH" = "8";
      "MAIL_DRIVER" = "smtp";
      "MAIL_ENCRYPTION" = "true";
      "MAIL_FROM" = "noreply@example.com";
      "MAIL_HOST" = "mail";
      "MAIL_PASSWORD" = "";
      "MAIL_PORT" = "1025";
      "MAIL_USERNAME" = "";
      "QUEUE_DRIVER" = "redis";
      "REDIS_HOST" = "cache";
      "SESSION_DRIVER" = "redis";
    };
    volumes = [
      "/srv/pterodactyl/certs/:/etc/letsencrypt:rw"
      "/srv/pterodactyl/logs/:/app/storage/logs:rw"
      "/srv/pterodactyl/nginx/:/etc/nginx/http.d:rw"
      "/srv/pterodactyl/storage/:/app/storage/app/public:rw"
      "/srv/pterodactyl/var/:/app/var:rw"
    ];
    ports = [
      "127.0.0.1:80:80/tcp"
    ];
    dependsOn = [
      "hydrodactyl-panel-cache"
      "hydrodactyl-panel-database"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=panel"
      "--network=hydrodactyl-panel_default"
    ];
  };
  systemd.services."docker-hydrodactyl-panel-panel" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    unitConfig.Description = "Container hydrodactyl-panel-panel generated by compose2nix.";
    after = [
      "docker-network-hydrodactyl-panel_default.service"
    ];
    requires = [
      "docker-network-hydrodactyl-panel_default.service"
    ];
    partOf = [
      "docker-compose-hydrodactyl-panel-root.target"
    ];
    wantedBy = [
      "docker-compose-hydrodactyl-panel-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-hydrodactyl-panel_default" = {
    unitConfig.Description = "Network hydrodactyl-panel_default generated by compose2nix.";
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f hydrodactyl-panel_default";
    };
    script = ''
      docker network inspect hydrodactyl-panel_default || docker network create hydrodactyl-panel_default --subnet=172.20.0.0/16
    '';
    partOf = [ "docker-compose-hydrodactyl-panel-root.target" ];
    wantedBy = [ "docker-compose-hydrodactyl-panel-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-hydrodactyl-panel-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
